[project]
name = "examen-parcial-1"
version = "0.1.0"
description = "Examen parcial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
]
